spring:
  application:
    name: trackSmart

  datasource:
    url: jdbc:postgresql://user-db:5432/user_db
    username: raanan
    password: ${POSTGRES_PASSWORD}

  flyway:
    enabled: true
    locations: classpath:db/user_db

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: tracksmart-consumers

  logging:
    level:
      org:
        springframework: INFO
      com:
        example:
          trackSmart: DEBUG

jwt:
  secret: ${JWT_SECRET}

report:
  datasource:
    url: jdbc:postgresql://report-db:5433/report_db
    username: raanan
    password: ${POSTGRES_PASSWORD}

notification:
  datasource:
    url: jdbc:postgresql://notification-db:5434/notification_db
    username: raanan
    password: ${POSTGRES_PASSWORD}
